Repository AY2122S1-CS2113-T16-4/tp, pull requests merged in 2021-11, with the labels that each got.

#91 Fix some documentation issue in User Guide
  docs/UserGuide.md
Labels: bug.severity.VeryLow, type.Bug

#92 Fix ped bugs
  docs/UserGuide.md
  src/main/java/command/expense/AddExpenseCommand.java
  src/main/java/constants/ErrorMessage.java
  src/main/java/entity/expense/ExpenseList.java
  src/main/java/service/ExpenseManager.java
Labels: bug.severity.High, priority.High, type.Bug

#101 Add unit tests for expense
  docs/team/mohamedirfansh.md
  src/main/java/constants/WarningMessage.java
  src/main/java/entity/expense/ExpenseList.java
  src/main/java/service/ExpenseManager.java
  src/test/java/command/budget/AddBudgetCommandTest.java
  src/test/java/command/budget/DeleteBudgetCommandTest.java
  src/test/java/command/expense/AddExpenseCommandTest.java
  src/test/java/command/expense/DeleteExpenseCommandTest.java
  src/test/java/command/income/AddIncomeCommandTest.java
  src/test/java/command/income/DeleteIncomeCommandTest.java
  src/test/java/command/invest/AddSavingCommandTest.java
  src/test/java/command/invest/AddStockCommandTest.java
  src/test/java/command/invest/DeleteSavingCommandTest.java
  src/test/java/command/invest/DeleteStockCommandTest.java
  src/test/java/entity/expense/ExpenseListTest.java
  src/test/java/entity/expense/ExpenseTest.java
  src/test/java/service/ExpenseManagerTest.java
Labels: priority.High

#103 fix the issue that a negative value can be updated in income manager
  src/main/java/command/income/UpdateIncomeCommand.java
Labels: priority.Medium
